#!/bin/sh

#██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
#██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
#██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║     
#██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║     
#██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
#╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝

bspc rule -r "*"
# set root pointer
xsetroot -cursor_name left_ptr

# key bindings
pkill sxhkd
sxhkd&

# panel
pkill polybar
polybar -c ~/.config/polybar/config.ini main &

# start compositor
picom -b &

# Set some bsp specific stuff
bspc monitor eDP1 -d I II III IV V
bspc monitor HDMI2 -d VI VII VIII IX X

bspc config window_gap 0
bspc config border_width 2

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config pointer_modifier shift
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config focus_follows_pointer true


#visual options
bspc config normal_border_color "#1c2023"
bspc config active_border_color "#1c2023"
bspc config focused_border_color "#8fa1b3"

#rules
bspc rule -a Zathura state=tiled
bspc rule -a URxvt:urxvt_keys_help state=floating
bspc rule -a Spacefm state=floating center=true rectangle=1376x625+0+0
bspc rule -a URxvt:urxvt_open state=floating

#wallpaper
nitrogen --restore

#autostart
# pkill owncloud
# owncloud&
pkill blueberry-tray
blueberry-tray&
# pkill nextcloud
# nextcloud&
# pkill protonmail-bridge
# protonmail-bridge&

#startup scripts
#        ~/scripts/spotify/launchlistener.sh
